stages:
  - build
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - echo "Starting to build"
    - export TAG_VERSION=$TAG_COMMIT.$(date +%y.%m.%d)
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo docker build -t $TAG_VERSION -t $TAG_LATEST .
    - sudo docker push $TAG_VERSION
    - sudo docker push $TAG_LATEST
  only:
    - staging
    - prod
  tags:
    - cicd
